// import { createSlice } from "@reduxjs/toolkit";

// const initialState = {
//   items: [
//     {
//       id: "1",
//       title: "Chocolate Delight Hamper",
//       sellerId:"seller1",
//       sellerName: "Sweet Treats",
//       sellerRating: 4.7,
//       sellerReviews: 210,
//       stock: 10,
//       image: ["https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400",
//               "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400",
//               "https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400",
//               ],
//       price: 2000,
//       originalPrice: 2500,
//       rating: 4,
//       reviews: 120,
//       reviewsData: [
//           {
//             id: 1,
//             name: "Anjali",
//             rating: 5,
//             title: "Amazing Gift!",
//             comment: "Beautiful packaging and great quality products.",
//             date: "2 days ago",
//           },
//           {
//             id: 2,
//             name: "Rahul",
//             rating: 4,
//             title: "Worth it",
//             comment: "Good hamper, delivery was fast.",
//             date: "1 week ago",
//           },
//         ],
//       description:
//             "A delightful chocolate hamper filled with premium chocolates, perfect for gifting on birthdays and special occasions.",
//       features: [
//             "Premium imported chocolates",
//             "Beautiful gift packaging",
//             "Custom message card included",
//       ],
//       tags: ["Chocolate", "Birthday", "Gift Hamper"],
//       mainCategory: "Occasion",
//       subCategory: "Birthday",
//       giftTypes: ["Handmade", "Luxury"],
//       isFeatured: true,
//       customizable: true,
//       customizations: [
//   {
//     type: "text",
//     label: "Gift Message",
//     key: "message"
//   },
//   {
//     type: "text",
//     label: "Recipient Name",
//     key: "recipientName"
//   },
//   {
//     type: "dropdown",
//     label: "Color",
//     key: "color",
//     options: ["Pink", "Blue"]
//   }
// ]
//     },
//     {
//       id: "2",
//       title: "Luxury Gift Box",
//       sellerName: "Gift Studio",
//       sellerId:"seller2",
//       sellerRating: 4.7,
//       sellerReviews: 210,
//       stock:5,
//       image: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=400"],
//       price: 2000,
//       originalPrice: 2500,
//       rating: 4.2,
//       reviews: 80,
//       mainCategory: "Recipient",
//       subCategory: "For Her",
//       giftTypes: ["Luxury"],
//       isFeatured: true,
//       customizable: true,
//     },
//     {
//       id: "3",
//       title: "Watch Hamper",
//       sellerId:"seller3",
//       sellerName: "seller shop name",
//       sellerRating: 4.7,
//       sellerReviews: 210,
//       stock:5,
//       image: ["https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400"],
//       price: 2000,
//       originalPrice: 2500,
//       rating: 4,
//       reviews: 60,
//       mainCategory: "Recipient",
//       subCategory: "for Him",
//       giftTypes: ["Handmade", "Luxury"],
//        isFeatured: true,
//        customizable:true,
//     },
//     {
//       id: "4",
//       title: "Festival Hamperd",
//       sellerId:"seller4",
//       sellerName: "seller shop name",
//       sellerRating: 4.7,
//       sellerReviews: 210,
//       stock:5,
//       image: ["https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400"],
//       price: 2000,
//       originalPrice: 2500,
//       rating: 4,
//       reviews: 60,
//       mainCategory: "Festival",
//       subCategory: "Diwali",
//       giftTypes: ["Self Care"],
//        isFeatured: true,
//        customizable:true,
//     },
//     {
//       id: "5",
//       title: "Festival Hamperd",
//       sellerId:"seller5",
//       sellerName: "seller shop name",
//       sellerRating: 4.7,
//       sellerReviews: 210,
//       stock:5,
//       image: ["https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400"],
//       price: 2000,
//       originalPrice: 2500,
//       rating: 4,
//       reviews: 60,
//       mainCategory: "Festival",
//       subCategory: "Diwali",
//       giftTypes: ["Snack Hamper", "Self Care"],
//        isFeatured: true,
//        customizable:true,
//     },
//     {
//       id: "6",
//       title: "Festival Hamperz",
//       sellerId:"seller6",
//       sellerName: "seller shop name",
//       sellerRating: 4.7,
//       sellerReviews: 210,
//       stock:5,
//       image: ["https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400"],
//       price: 2000,
//       originalPrice: 2500,
//       rating: 4,
//       reviews: 60,
//       mainCategory: "Festival",
//       subCategory: "Diwali",
//        isFeatured: true,
//        customizable:true,
//     },
//     {
//       id: "7",
//       title: "Handmade Hamperf",
//       sellerId:"seller7",
//       sellerName: "seller shop name",
//       sellerRating: 4.7,
//       sellerReviews: 210,
//       stock:5,
//       image: ["https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400"],
//       price: 2100,
//       originalPrice: 2500,
//       rating: 4,
//       reviews: 60,
//       mainCategory: "Festival",
//       subCategory: "New Year",
//        giftTypes: ["Handmade"],
//        isFeatured: true,
//        customizable:true,
//     },
//     {
//       id: "8",
//       title: "Festival HamperN",
//       sellerId:"seller8",
//       sellerName: "seller shop name",
//       sellerRating: 4.7,
//       sellerReviews: 210,
//       stock:5,
//       image: ["https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400"],
//       price: 2200,
//       originalPrice: 2500,
//       rating: 4,
//       reviews: 60,
//       mainCategory: "Festival",
//       subCategory: "New Year",
//       giftTypes: ["Dry Fruit Hamper"],
//        isFeatured: false,
//        customizable:true,
       
//     },
//   ],
// };

// const productSlice = createSlice({
//   name: "products",
//   initialState,
//   reducers: {
//     // later you can add filters here
//   },
// });

// export default productSlice.reducer;

import { createSlice } from "@reduxjs/toolkit";


const initialState = {
  items: [
   
    {
      id: "1",
      title: "Chocolate Delight Hamper",
      sellerId: "seller1",
      sellerName: "Sweet Treats",
      sellerRating: 4.7,
      sellerReviews: 210,
      stock: 10,
      image: [
        "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400",
        "https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400",
      ],
      price: 2000,
      originalPrice: 2500,
      rating: 4,
      reviews: 120,
      reviewsData: [
        { id: 1, name: "Anjali",  rating: 5, title: "Amazing Gift!",  comment: "Beautiful packaging and great quality products.", date: "2 days ago" },
        { id: 2, name: "Rahul",   rating: 4, title: "Worth it",       comment: "Good hamper, delivery was fast.",                 date: "1 week ago" },
      ],
      description: "A delightful chocolate hamper filled with premium chocolates, perfect for gifting on birthdays and special occasions.",
      features: ["Premium imported chocolates", "Beautiful gift packaging", "Custom message card included"],
      tags: ["Chocolate", "Birthday", "Gift Hamper"],
      mainCategory: "Occasion",
      subCategory: "birthday",
      giftTypes: ["handmade", "luxury"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text",     label: "Gift Message",   key: "message"       },
        { type: "text",     label: "Recipient Name", key: "recipientName" },
        { type: "dropdown", label: "Color",          key: "color", options: ["Pink", "Blue"] },
      ],
    },
    {
      id: "9",
      title: "Birthday Balloon & Candle Hamper",
      sellerId: "seller9",
      sellerName: "Party Palace",
      sellerRating: 4.5,
      sellerReviews: 98,
      stock: 15,
      image: ["https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400"],
      price: 1299,
      originalPrice: 1799,
      rating: 4.3,
      reviews: 74,
      reviewsData: [
        { id: 1, name: "Priya", rating: 5, title: "So cute!", comment: "Loved the packaging, very festive.", date: "3 days ago" },
      ],
      description: "Celebrate birthdays in style with this cheerful hamper featuring scented candles, mini chocolates, and party essentials.",
      features: ["Scented soy candles", "Assorted mini chocolates", "Balloon set included", "Personalised banner"],
      tags: ["Birthday", "Celebration"],
      mainCategory: "Occasion",
      subCategory: "birthday",
      giftTypes: ["handmade", "Personalized"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text", label: "Name on Banner", key: "bannerName" },
      ],
    },

   
    {
      id: "10",
      title: "Anniversary Rose & Wine Hamper",
      sellerId: "seller10",
      sellerName: "BlossomGifts",
      sellerRating: 4.8,
      sellerReviews: 312,
      stock: 8,
      image: [
        "https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400",
        "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=400",
      ],
      price: 2299,
      originalPrice: 2999,
      rating: 4.6,
      reviews: 218,
      reviewsData: [
        { id: 1, name: "Sneha", rating: 5, title: "Perfect anniversary gift!", comment: "My partner loved it. Super premium feel.", date: "1 week ago" },
        { id: 2, name: "Arjun", rating: 4, title: "Great packaging",          comment: "Arrived beautifully packed.",              date: "2 weeks ago" },
      ],
      description: "A luxurious anniversary hamper with premium rose petals, artisan chocolates, scented candles and a personalised message card.",
      features: ["Preserved rose petals", "Dark chocolate truffles", "Lavender scented candle", "Personalised message card"],
      tags: ["Anniversary", "Romantic", "For Her"],
      mainCategory: "Occasion",
      subCategory: "anniversary",
      giftTypes: ["luxury", "Personalized"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text",     label: "Your Message",   key: "message"      },
        { type: "dropdown", label: "Rose Colour",    key: "roseColour", options: ["Red", "Pink", "White"] },
      ],
    },

 
    {
      id: "2",
      title: "Luxury Pamper Gift Box for Her",
      sellerName: "Gift Studio",
      sellerId: "seller2",
      sellerRating: 4.7,
      sellerReviews: 210,
      stock: 5,
      image: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=400"],
      price: 2000,
      originalPrice: 2500,
      rating: 4.2,
      reviews: 80,
      reviewsData: [
        { id: 1, name: "Meera", rating: 4, title: "Beautiful box", comment: "Great quality items inside.", date: "5 days ago" },
      ],
      description: "An indulgent pamper hamper packed with skincare essentials, bath bombs and premium fragrances — perfect for the special woman in your life.",
      features: ["Rose face mask", "Bath bomb set", "Luxury body lotion", "Scented candle"],
      tags: ["For Her", "Self Care", "Birthday"],
      mainCategory: "Recipient",
      subCategory: "for her",
      giftTypes: ["luxury", "Self Care"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text", label: "Gift Message", key: "message" },
      ],
    },
    {
      id: "11",
      title: "Self-Care Wellness Hamper",
      sellerId: "seller11",
      sellerName: "WarmGifts",
      sellerRating: 4.6,
      sellerReviews: 145,
      stock: 12,
      image: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=400"],
      price: 1199,
      originalPrice: 1599,
      rating: 4.7,
      reviews: 94,
      reviewsData: [
        { id: 1, name: "Kavya", rating: 5, title: "Best self-care gift!", comment: "Absolutely loved every item.", date: "2 days ago" },
      ],
      description: "Treat yourself or someone special with this thoughtfully curated wellness hamper — aromatherapy, skincare and more.",
      features: ["Aromatherapy candle", "Herbal tea selection", "Face serum", "Stress-relief bath salt"],
      tags: ["Self Care", "Wellness", "For Her"],
      mainCategory: "Recipient",
      subCategory: "for her",
      giftTypes: ["wellness", "Self Care", "luxury"],
      isFeatured: true,
      customizable: false,
    },

  
    {
      id: "3",
      title: "Premium Watch & Accessories Hamper",
      sellerId: "seller3",
      sellerName: "GiftForHim",
      sellerRating: 4.7,
      sellerReviews: 210,
      stock: 5,
      image: ["https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400"],
      price: 2000,
      originalPrice: 2500,
      rating: 4,
      reviews: 60,
      reviewsData: [],
      description: "A sophisticated hamper for him featuring premium accessories, grooming essentials and artisan treats.",
      features: ["Premium grooming kit", "Artisan chocolates", "Personalised card"],
      tags: ["For Him", "Birthday", "luxury"],
      mainCategory: "Recipient",
      subCategory: "for him",
      giftTypes: ["handmade", "Luxury"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text", label: "Engraving Text", key: "engraving" },
      ],
    },
    {
      id: "12",
      title: "Snacks & Gaming Night Hamper for Him",
      sellerId: "seller12",
      sellerName: "ManCave Gifts",
      sellerRating: 4.4,
      sellerReviews: 88,
      stock: 20,
      image: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=400"],
      price: 1499,
      originalPrice: 1999,
      rating: 4.3,
      reviews: 52,
      reviewsData: [],
      description: "The ultimate snack hamper for the guy who loves gaming nights — loaded with premium snacks, energy drinks and treats.",
      features: ["Assorted premium snacks", "Energy drinks selection", "Popcorn varieties", "Chocolate bars"],
      tags: ["For Him", "Snack Hamper", "Birthday"],
      mainCategory: "Recipient",
      subCategory: "for him",
      giftTypes: ["Snack Hamper"],
      isFeatured: false,
      customizable: false,
    },

  
    {
      id: "13",
      title: "Kids Fun Activity & Candy Hamper",
      sellerId: "seller13",
      sellerName: "TinyJoys",
      sellerRating: 4.9,
      sellerReviews: 276,
      stock: 18,
      image: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400"],
      price: 899,
      originalPrice: 1199,
      rating: 4.8,
      reviews: 143,
      reviewsData: [
        { id: 1, name: "Deepa", rating: 5, title: "Kids loved it!", comment: "My kids were thrilled. Excellent quality.", date: "1 day ago" },
      ],
      description: "A delightful hamper for kids bursting with activity kits, candies, mini toys and art supplies — perfect for birthdays.",
      features: ["Art & craft kit", "Assorted candies", "Mini puzzle game", "Colouring book"],
      tags: ["For Kids", "Birthday", "Handmade"],
      mainCategory: "Recipient",
      subCategory: "kids",
      giftTypes: ["handmade", "Personalized"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text", label: "Child's Name", key: "childName" },
      ],
    },


    {
      id: "14",
      title: "Premium Corporate Gift Hamper",
      sellerId: "seller14",
      sellerName: "CorpGifts",
      sellerRating: 4.6,
      sellerReviews: 189,
      stock: 50,
      image: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=400"],
      price: 1899,
      originalPrice: 2499,
      rating: 4.5,
      reviews: 112,
      reviewsData: [],
      description: "A refined corporate gift hamper featuring premium dry fruits, artisan biscuits, branded stationery and a personalised message card.",
      features: ["Premium dry fruit mix", "Artisan biscuit selection", "Branded notebook", "Personalised message card"],
      tags: ["Corporate Gifts", "Dry Fruit Hamper", "Luxury"],
      mainCategory: "Recipient",
      subCategory: "corporate",
      giftTypes: ["luxury", "Dry Fruit Hamper"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text", label: "Company Name",  key: "companyName" },
        { type: "text", label: "Message",       key: "message"     },
      ],
    },

    
    {
      id: "4",
      title: "Diwali Festive Dry Fruit & Sweets Hamper",
      sellerId: "seller4",
      sellerName: "FestiveLane",
      sellerRating: 4.7,
      sellerReviews: 210,
      stock: 0,                      // out of stock — tests OOS UI
      image: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400"],
      price: 899,
      originalPrice: 1299,
      rating: 4.5,
      reviews: 156,
      reviewsData: [],
      description: "Celebrate Diwali with this festive hamper packed with premium dry fruits, traditional sweets and decorative diyas.",
      features: ["Premium cashew & almond mix", "Traditional Indian sweets", "Decorative diya set", "Festive packaging"],
      tags: ["Diwali", "Dry Fruit Hamper", "Snack Hamper"],
      mainCategory: "Festival",
      subCategory: "diwali",
      giftTypes: ["Dry Fruit Hamper", "Self Care"],
      isFeatured: true,
      customizable: false,
    },
    {
      id: "5",
      title: "Diwali Premium Snack Celebration Box",
      sellerId: "seller5",
      sellerName: "FestiveLane",
      sellerRating: 4.7,
      sellerReviews: 210,
      stock: 5,
      image: ["https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400"],
      price: 2000,
      originalPrice: 2500,
      rating: 4,
      reviews: 60,
      reviewsData: [],
      description: "A grand Diwali snack hamper with premium mithai, namkeen and beautifully crafted festive packaging.",
      features: ["Assorted premium namkeen", "Kaju katli & ladoo", "Saffron dry fruits", "Festive tin box"],
      tags: ["Diwali", "Snack Hamper"],
      mainCategory: "Festival",
      subCategory: "diwali",
      giftTypes: ["Snack Hamper", "Self Care"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text", label: "Personalised Note", key: "note" },
      ],
    },
    {
      id: "6",
      title: "Diwali Luxury Gold Collection Hamper",
      sellerId: "seller6",
      sellerName: "GoldGifts",
      sellerRating: 4.7,
      sellerReviews: 210,
      stock: 5,
      image: ["https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400"],
      price: 2000,
      originalPrice: 2500,
      rating: 4,
      reviews: 60,
      reviewsData: [],
      description: "Celebrate Diwali with opulence — this gold-themed luxury hamper features premium chocolates, golden dry fruit mix and scented diyas.",
      features: ["Belgian dark chocolates", "Gold-dusted almond mix", "Scented premium diya", "Gold foil gift box"],
      tags: ["Diwali", "luxury"],
      mainCategory: "Festival",
      subCategory: "diwali",
      giftTypes: ["Luxury"],
      isFeatured: true,
      customizable: true,
      customizations: [],
    },


    {
      id: "7",
      title: "New Year Handcrafted Celebration Hamper",
      sellerId: "seller7",
      sellerName: "ArtisanGifts",
      sellerRating: 4.7,
      sellerReviews: 210,
      stock: 5,
      image: ["https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400"],
      price: 2100,
      originalPrice: 2500,
      rating: 4,
      reviews: 60,
      reviewsData: [],
      description: "Welcome the New Year with this handcrafted celebration hamper full of artisan goodies and party essentials.",
      features: ["Handmade chocolates", "Sparkling juice bottle", "Party poppers & confetti", "Personalised countdown card"],
      tags: ["New Year", "handmade", "Celebration"],
      mainCategory: "Festival",
      subCategory: "new-year",
      giftTypes: ["Handmade"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text", label: "New Year Wish", key: "wish" },
      ],
    },
    {
      id: "8",
      title: "New Year Dry Fruit & Nut Premium Hamper",
      sellerId: "seller8",
      sellerName: "NutriGifts",
      sellerRating: 4.7,
      sellerReviews: 210,
      stock: 5,
      image: ["https://images.unsplash.com/photo-1607083206968-13611e3d76db?w=400"],
      price: 2200,
      originalPrice: 2500,
      rating: 4,
      reviews: 60,
      reviewsData: [],
      description: "Ring in the New Year with health and prosperity — this premium dry fruit hamper makes the perfect gifting choice.",
      features: ["Premium cashews & almonds", "Mixed berries & figs", "Saffron threads", "Elegant wooden tray"],
      tags: ["New Year", "Dry Fruit Hamper"],
      mainCategory: "Festival",
      subCategory: "new-year",
      giftTypes: ["Dry Fruit Hamper"],
      isFeatured: false,
      customizable: true,
      customizations: [],
    },

    
    {
      id: "15",
      title: "Christmas Classic Hamper",
      sellerId: "seller15",
      sellerName: "WinterJoy",
      sellerRating: 4.8,
      sellerReviews: 167,
      stock: 14,
      image: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400"],
      price: 1799,
      originalPrice: 2299,
      rating: 4.7,
      reviews: 98,
      reviewsData: [
        { id: 1, name: "Sam", rating: 5, title: "Magical!", comment: "Perfect Christmas gift. Loved the packaging.", date: "1 week ago" },
      ],
      description: "Spread Christmas cheer with this classic hamper featuring mulled wine spices, gingerbread, premium chocolates and a festive candle.",
      features: ["Mulled wine spice kit", "Gingerbread biscuits", "Premium dark chocolates", "Cinnamon scented candle"],
      tags: ["Christmas", "Luxury", "Snack Hamper"],
      mainCategory: "Festival",
      subCategory: "christmas",
      giftTypes: ["luxury", "Snack Hamper"],
      isFeatured: true,
      customizable: false,
    },

   
    {
      id: "16",
      title: "Valentine's Day Love Hamper",
      sellerId: "seller16",
      sellerName: "LoveGifts",
      sellerRating: 4.9,
      sellerReviews: 241,
      stock: 7,
      image: ["https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=400"],
      price: 1599,
      originalPrice: 1999,
      rating: 4.8,
      reviews: 184,
      reviewsData: [
        { id: 1, name: "Ria",  rating: 5, title: "She loved it!",    comment: "Perfect Valentine's gift. Will order again.", date: "2 weeks ago" },
        { id: 2, name: "Kiran", rating: 5, title: "Super romantic!", comment: "The packaging was stunning.",                 date: "1 month ago" },
      ],
      description: "Express your love with this romantic hamper — heart-shaped chocolates, rose perfume, scented candles and a personalised love letter card.",
      features: ["Heart-shaped Belgian chocolates", "Rose & jasmine perfume mist", "Love letter greeting card", "Satin ribbon gift box"],
      tags: ["Valentines Day", "For Her", "Romantic"],
      mainCategory: "Festival",
      subCategory: "valentines",
      giftTypes: ["luxury", "Personalized"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text",     label: "Love Message",      key: "message"   },
        { type: "dropdown", label: "Box Colour",        key: "boxColour", options: ["Red", "Pink", "White"] },
      ],
    },

    
    {
      id: "17",
      title: "Coffee & Tea Hamper",
      sellerId: "seller17",
      sellerName: "BrewBox",
      sellerRating: 4.5,
      sellerReviews: 132,
      stock: 22,
      image: ["https://images.unsplash.com/photo-1516961642265-531546e84af2?w=400"],
      price: 1099,
      originalPrice: 1499,
      rating: 4.6,
      reviews: 79,
      reviewsData: [],
      description: "A curated hamper for the tea and coffee lover — featuring single-origin coffees, premium herbal teas and artisan biscuits.",
      features: ["Single-origin pour-over coffee", "Assorted herbal teas", "Artisan shortbread biscuits", "Reusable bamboo mug"],
      tags: ["Coffee & Tea", "Wellness", "Birthday"],
      mainCategory: "Festival",
      subCategory: "valentines",
      giftTypes: ["Coffee & Tea", "wellness"],
      isFeatured: false,
      customizable: false,
    },

 
    {
      id: "18",
      title: "Handmade Gratitude Thank You Hamper",
      sellerId: "seller18",
      sellerName: "CurateCo",
      sellerRating: 4.4,
      sellerReviews: 76,
      stock: 20,
      image: ["https://images.unsplash.com/photo-1516961642265-531546e84af2?w=400"],
      price: 649,
      originalPrice: 899,
      rating: 4.4,
      reviews: 67,
      reviewsData: [],
      description: "A heartfelt handmade hamper to say thank you — featuring hand-poured candles, artisan soaps and a handwritten note card.",
      features: ["Hand-poured soy candle", "Artisan goat milk soap", "Handwritten note card", "Wildflower seed packet"],
      tags: ["Thank You", "Handmade", "Wellness"],
      mainCategory: "Festival",
      subCategory: "mothers-day",
      giftTypes: ["handmade", "wellness"],
      isFeatured: false,
      customizable: true,
      customizations: [
        { type: "text", label: "Personalised Note", key: "note" },
      ],
    },

  
    {
      id: "19",
      title: "Baby Shower Welcome Little One Hamper",
      sellerId: "seller19",
      sellerName: "TinyJoys",
      sellerRating: 4.9,
      sellerReviews: 276,
      stock: 5,
      image: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400"],
      price: 1799,
      originalPrice: 2299,
      rating: 4.9,
      reviews: 183,
      reviewsData: [
        { id: 1, name: "Naina", rating: 5, title: "Adorable!", comment: "New mum was so happy. Great quality items.", date: "3 days ago" },
      ],
      description: "Celebrate the arrival of a new baby with this adorable hamper packed with baby essentials, organic products and sweet treats for the new mum.",
      features: ["Organic cotton muslin wrap", "Baby skincare essentials kit", "New mum chocolate selection", "Handmade knitted baby booties"],
      tags: ["Baby Shower", "For Her", "Handmade"],
      mainCategory: "Occasion",
      subCategory: "baby-shower",
      giftTypes: ["handmade", "Personalized", "Self Care"],
      isFeatured: true,
      customizable: true,
      customizations: [
        { type: "text",     label: "Baby's Name",  key: "babyName" },
        { type: "dropdown", label: "Colour Theme", key: "theme", options: ["Pink", "Blue", "Neutral Yellow"] },
      ],
    },

    {
      id: "20",
      title: "Get Well Soon Care & Comfort Hamper",
      sellerId: "seller20",
      sellerName: "CareBox",
      sellerRating: 4.6,
      sellerReviews: 118,
      stock: 16,
      image: ["https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400"],
      price: 999,
      originalPrice: 1399,
      rating: 4.6,
      reviews: 88,
      reviewsData: [
        { id: 1, name: "Lakshmi", rating: 5, title: "So thoughtful!", comment: "Perfect gift for someone recovering. They felt so cared for.", date: "4 days ago" },
      ],
      description: "Send warm wishes with this thoughtful get-well hamper — herbal teas, nourishing soups, honey and comforting treats for a speedy recovery.",
      features: ["Immunity-boosting herbal teas", "Organic raw honey", "Nourishing instant soup sachets", "Lavender relaxation eye mask"],
      tags: ["Get Well Soon", "Wellness", "Coffee & Tea"],
      mainCategory: "Occasion",
      subCategory: "wellness",
      giftTypes: ["wellness", "Coffee & Tea", "Self Care"],
      isFeatured: false,
      customizable: true,
      customizations: [
        { type: "text", label: "Recovery Message", key: "message" },
      ],
    },
  ],
};

const productSlice = createSlice({
  name: "products",
  initialState,
  reducers: {
    /* Add reducers here when you connect to a backend:
       e.g. setProducts, updateStock, etc. */
  },
});
export const selectProducts = (state) => state.products.items;

export default productSlice.reducer;
